name: Compile Kernel Moto G8 (Native GCC)

on:
  push:
    branches: [ "lineage-18.1", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Sukisu Ultra
        run: |
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main

      - name: Install Dependencies
        run: |
          sudo apt update && sudo apt install -y \
            git device-tree-compiler lz4 xz-utils zlib1g-dev openjdk-17-jdk gcc g++ python3 python-is-python3 \
            p7zip-full android-sdk-libsparse-utils erofs-utils flex bison gperf build-essential zip curl \
            libc6-dev libncurses-dev libx11-dev libreadline-dev libgl1 libgl1-mesa-dev bc grep \
            libxml2-utils xsltproc kmod openssl libelf-dev pahole libssl-dev libarchive-tools zstd rsync \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Build Kernel
        run: |
          export KERNEL_ROOT="$(pwd)"
          export ARCH=arm64
          export KBUILD_BUILD_USER="@ravindu644"

          BUILD_CROSS_COMPILE="aarch64-linux-gnu-"

          mkdir -p "${KERNEL_ROOT}/out" "${KERNEL_ROOT}/build"

          # 1. Generate defconfig
          make -C "${KERNEL_ROOT}" O="${KERNEL_ROOT}/out" -j$(nproc) \
            ARCH=arm64 \
            CROSS_COMPILE="${BUILD_CROSS_COMPILE}" \
            vendor/sofiar_defconfig

          # Desativar MODVERSIONS para evitar erros de CRC
          cd "${KERNEL_ROOT}/out"
          ../scripts/config --disable CONFIG_MODVERSIONS
          cd "${KERNEL_ROOT}"

          # 2. Compile Image com GCC nativo
          make -C "${KERNEL_ROOT}" O="${KERNEL_ROOT}/out" -j$(nproc) \
            ARCH=arm64 \
            CROSS_COMPILE="${BUILD_CROSS_COMPILE}" \
            Image

          cp "${KERNEL_ROOT}/out/arch/arm64/boot/Image" "${KERNEL_ROOT}/build"

      - name: Upload Kernel Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-Image-Native
          path: build/Image
